services:
  application:
    env_file:
      - .env
      - .env.test
    depends_on:
      db:
        condition: service_healthy

  db:
    environment:
      POSTGRES_DB: ${ORO_DB_NAME_TEST:-oro_db_test}
    {{if .UseTmpfs -}}
    tmpfs:
      - /var/lib/postgresql/data:size={{.TmpfsSize}}
    {{- end}}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 60s
