x-templates:
  oro-app: &oro-app
    image: "algoritmadev/orobox:{{.OroVersion}}-{{.Type}}-latest"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  volumes-setup: &volumes-setup
    {{if eq .Type "project" -}}
    - "{{.BundlePath}}:/var/www/oro"
    {{- else -}}
    - "oro_app:/var/www/oro"
    {{if eq .Type "bundle" -}}
    - "{{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}"
    {{- end}}
    - "public_storage:/var/www/oro/public/media"
    - "private_storage:/var/www/oro/var/data"
    {{- end}}

services:
  volume-setup:
    <<: *oro-app
    user: root
    command:
      - bash
      - -c
      - |
        echo "Initializing volumes and permissions for ${ORO_USER_RUNTIME:-www-data}..."
        mkdir -p bin config public src templates translations var assets var/cache var/logs var/data public/media
        chown -R ${ORO_USER_RUNTIME:-www-data} . bin config public src templates translations var assets var/cache var/logs var/data public/media 2>/dev/null || true
        chmod -R 777 var/cache var/logs var/data 2>/dev/null || true
        true
    environment:
      ORO_XDEBUG_ENABLED: "false"
    volumes: *volumes-setup

  install:
    <<: *oro-app
    command: install ${ORO_INSTALL_OPTIONS}
    user: ${ORO_USER_RUNTIME:-www-data}
    environment:
      ORO_SAMPLE_DATA: ${ORO_SAMPLE_DATA:-y}
      ORO_XDEBUG_ENABLED: ${ORO_INSTALL_XDEBUG_ENABLED:-false}
    depends_on:
      "volume-setup":
        condition: service_completed_successfully
      "gotenberg":
        condition: service_healthy
      {{if .Postgres -}}
      "db":
        condition: service_healthy
      {{- end}}
      {{if .Mailpit -}}
      "mail":
        condition: service_started
      {{- end}}
      {{if .Redis -}}
      "redis":
        condition: service_healthy
      {{- end}}
      {{if .RabbitMQ -}}
      "rabbitmq":
        condition: service_started
      {{- end}}
      {{if .Elasticsearch -}}
      "elasticsearch":
        condition: service_started
      {{- end}}
    volumes: *volumes-setup
