
services:
  application:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    command:
      - bash
      - -c
      - |
        echo "Application is running..."
        {{range .Domains -}}
        echo "Listen on: {{if .Ssl}}https://{{.Host}}{{if ne $.NginxHTTPSPort "443"}}:{{$.NginxHTTPSPort}}{{end}}{{else}}http://{{.Host}}{{if ne $.NginxHTTPPort "80"}}:{{$.NginxHTTPPort}}{{end}}{{end}}/"
        {{else -}}
        echo "Listen on: $${ORO_APP_PROTOCOL}://$${ORO_APP_DOMAIN}{{if and (ne .NginxHTTPPort "80") (ne .NginxHTTPPort "443")}}:{{.NginxHTTPPort}}{{end}}/"
        {{end -}}
        exec tail -f /dev/null
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - oro_app:/var/www/oro
      - {{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}
      - cache:/var/www/oro/var/cache
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 1777
    tmpfs:
      - /run
    depends_on:
      "web":
        condition: service_started
      "consumer":
        condition: service_started
      "cron":
        condition: service_started

  web:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    environment:
      ORO_XDEBUG_ENABLED: "false"
    command: nginx
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    healthcheck:
      test: "curl -If http://127.0.0.1:{{.NginxHTTPPort}}/"
      interval: 15s
      timeout: 30s
      start_period: 15s
    ports:
      - published: {{.NginxHTTPPort}}
        target: {{.NginxHTTPPort}}
      {{if .HasSsl -}}
      - published: {{.NginxHTTPSPort}}
        target: {{.NginxHTTPSPort}}
      {{- end}}
    depends_on:
      "web-init":
        condition: service_completed_successfully
      "php-fpm-app":
        condition: service_healthy
    volumes:
      - oro_app:/var/www/oro
      - {{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}
      - cache:/var/www/oro/var/cache:ro
      - maintenance_folder:${ORO_MAINTENANCE_LOCK_FOLDER:-/var/www/oro/var/maintenance}
      - nginx:/opt/oro-nginx
      - public_storage:/var/www/oro/public/media:ro
      - private_storage:/var/www/oro/var/data:ro
      {{if .HasSsl -}}
      - {{.CertsPath}}:/etc/nginx/certs:ro
      {{- end}}

  volume-init:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    command: -- true
    env_file: .env
    environment:
      ORO_XDEBUG_ENABLED: "false"
    volumes:
      - oro_app:/var/www/oro
 
  web-init:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    command:
      - bash
      - -c
      - |
        echo "$$(jq '.properties.sites.propertyNames.pattern = ".*"' /opt/oro-nginx-tool/variables.schema.json 2>/dev/null || echo "{}")" > /opt/oro-nginx-tool/variables.schema.json 2>/dev/null || true
        /usr/local/bin/docker-entrypoint.sh nginx-init && sed -i '/gridfs/d; /mongo/d' /opt/oro-nginx/etc/sites-available/*.conf || true
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      ORO_XDEBUG_ENABLED: "false"
    depends_on:
      "php-fpm-app":
        condition: service_healthy
      "ws":
        condition: service_started
    volumes:
      - nginx:/opt/oro-nginx

  php-fpm-app:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    command: php-fpm
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 5s
      timeout: 30s
      start_period: 15s
    environment:
      ORO_ENV: ${ORO_ENV:-dev}
      ORO_LOG_PATH: php://stderr
    tmpfs:
      - /run
    depends_on:
      {{if .Postgres -}}
      "db":
        condition: service_healthy
      {{- end}}
      {{if .Mailpit -}}
      "mail":
        condition: service_started
      {{- end}}
      "volume-init":
        condition: service_completed_successfully
      {{if .Redis -}}
      "redis":
        condition: service_started
      {{- end}}
      {{if .RabbitMQ -}}
      "rabbitmq":
        condition: service_started
      {{- end}}
      {{if .Elasticsearch -}}
      "elasticsearch":
        condition: service_started
      {{- end}}
    volumes:
      - oro_app:/var/www/oro
      - {{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}
      - cache:/var/www/oro/var/cache
      - multihost_operation_folder:${ORO_MULTIHOST_OPERATION_FOLDER:-/var/www/oro/var/multihost}
      - maintenance_folder:${ORO_MAINTENANCE_LOCK_FOLDER:-/var/www/oro/var/maintenance}
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 1777

  ws:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    command: websocket
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    init: true
    environment:
      ORO_ENV: ${ORO_ENV:-dev}
      ORO_LOG_PATH: php://stderr
      ORO_XDEBUG_ENABLED: "false"
    tmpfs:
      - /run
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes:
      - oro_app:/var/www/oro
      - {{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}
      - cache:/var/www/oro/var/cache
      - maintenance_folder:${ORO_MAINTENANCE_LOCK_FOLDER:-/var/www/oro/var/maintenance}
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 1777

  consumer:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    command: consumer
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    init: true
    environment:
      ORO_ENV: ${ORO_ENV:-dev}
      ORO_LOG_PATH: php://stderr
      ORO_XDEBUG_ENABLED: ${ORO_CONSUMER_XDEBUG_ENABLED:-false}
    tmpfs:
      - /run
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes:
      - oro_app:/var/www/oro
      - {{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}
      - cache:/var/www/oro/var/cache
      - maintenance_folder:${ORO_MAINTENANCE_LOCK_FOLDER:-/var/www/oro/var/maintenance}
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 1777

  cron:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    command: cron
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 1048576
    environment:
      ORO_ENV: ${ORO_ENV:-dev}
      ORO_LOG_PATH: php://stderr
      ORO_XDEBUG_ENABLED: ${ORO_CRON_XDEBUG_ENABLED:-false}
    tmpfs:
      - /run
    volumes:
      - oro_app:/var/www/oro
      - {{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}
      - cache:/var/www/oro/var/cache
      - multihost_operation_folder:${ORO_MULTIHOST_OPERATION_FOLDER:-/var/www/oro/var/multihost}
      - maintenance_folder:${ORO_MAINTENANCE_LOCK_FOLDER:-/var/www/oro/var/maintenance}
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 1777
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    {{- if .Postgres}}
      "db":
        condition: service_healthy
    {{- end}}

  restore:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    command: restore
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: ${ORO_USER_RUNTIME:-www-data}
    env_file: .env
    environment:
      ORO_ENV: ${ORO_ENV:-dev}
      ORO_XDEBUG_ENABLED: "false"
    tmpfs:
      - /run
    depends_on:
      {{if .Postgres -}}
      "db":
        condition: service_healthy
      {{- end}}
      {{if .Mailpit -}}
      "mail":
        condition: service_started
      {{- end}}
      "volume-init":
        condition: service_completed_successfully
    volumes:
      - oro_app:/var/www/oro
      - {{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 1777

  install:
    image: orobox-app:{{.OroVersion}}-latest
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: {{.PHPVersion}}
        NODE_VERSION: {{.NodeVersion}}
        NPM_VERSION: {{.NpmVersion}}
        MEMORY_LIMIT: ${PHP_MEMORY_LIMIT:-2048M}
    command: install ${ORO_INSTALL_OPTIONS}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    user: ${ORO_USER_RUNTIME:-www-data}
    env_file: .env
    environment:
      ORO_SAMPLE_DATA: ${ORO_SAMPLE_DATA:-y}
      ORO_XDEBUG_ENABLED: ${ORO_INSTALL_XDEBUG_ENABLED:-false}
    tmpfs:
      - /run
    depends_on:
      {{if .Postgres -}}
      "db":
        condition: service_healthy
      {{- end}}
      {{if .Mailpit -}}
      "mail":
        condition: service_started
      {{- end}}
      {{if .Redis -}}
      "redis":
        condition: service_started
      {{- end}}
      {{if .RabbitMQ -}}
      "rabbitmq":
        condition: service_started
      {{- end}}
      {{if .Elasticsearch -}}
      "elasticsearch":
        condition: service_started
      {{- end}}
    volumes:
      - oro_app:/var/www/oro
      - {{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}
      - cache:/var/www/oro/var/cache
      - public_storage:/var/www/oro/public/media
      - private_storage:/var/www/oro/var/data
      - type: tmpfs
        target: /tmp
        tmpfs:
          mode: 1777

  {{if .Postgres}}
  db:
    image: postgres:{{.PostgresVersion}}
    labels:
      com.symfony.server.service-prefix: ORO_DB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${ORO_DB_NAME:-oro_db}
      POSTGRES_USER: ${ORO_DB_USER:-oro_db_user}
      POSTGRES_PASSWORD: ${ORO_DB_PASSWORD:-oro_db_pass}
      POSTGRES_ROOT_PASSWORD: ${ORO_DB_ROOT_PASSWORD:-oro_db_pass}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 60s
    restart: unless-stopped
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
  {{end}}
  {{if .Redis}}
  redis:
    image: redis:{{.RedisVersion}}
    hostname: redis
    restart: unless-stopped
  {{end}}
  {{if .Mailpit}}
  mail:
    image: axllent/mailpit
    hostname: mail
    ports:
      - "8025:8025"
      - "1025:1025"
    restart: unless-stopped
  {{end}}
  {{if .RabbitMQ}}
  rabbitmq:
    image: rabbitmq:{{.RabbitMQVersion}}
    hostname: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: ${ORO_RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${ORO_RABBITMQ_PASS:-guest}
  {{end}}
  {{if .Elasticsearch}}
  elasticsearch:
    image: elasticsearch:{{.ElasticsearchVersion}}
    hostname: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
  {{end}}
  gotenberg:
    image: gotenberg/gotenberg:8.23.2
    ports: [ "3000" ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3000/health" ]
    restart: on-failure

volumes:
  oro_app:
  cache:
  multihost_operation_folder:
  maintenance_folder:
  nginx:
  public_storage:
  private_storage:
