
x-templates:
  oro-app: &oro-app
    image: "algoritmadev/orobox:{{.OroVersion}}-{{.Type}}-latest"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        PHP_VERSION: "{{.PHPVersion}}"
        NODE_VERSION: "{{.NodeVersion}}"
        NPM_VERSION: "{{.NpmVersion}}"
        MEMORY_LIMIT: "${PHP_MEMORY_LIMIT:-2048M}"
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"

  volumes-oro: &volumes-oro
                 {{if eq .Type "project" -}}
                 - "{{.BundlePath}}:/var/www/oro"
    {{- else -}}
                 - "oro_app:/var/www/oro"
                 {{if eq .Type "bundle" -}}
                 - "{{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}"
    {{- end}}
                 - "cache:/var/www/oro/var/cache"
                 - "public_storage:/var/www/oro/public/media"
                 - "private_storage:/var/www/oro/var/data"
                 - "./nginx.conf:/etc/nginx/http.d/default.conf:ro"
                 - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro"
    {{- end}}

services:
  application:
    <<: *oro-app
    user: ${ORO_USER_RUNTIME:-www-data}
    command:
      - bash
      - -c
      - |
        echo "Application is running..."
        {{range .Domains -}}
        echo "Listen on: {{if .Ssl}}https://{{.Host}}{{if ne $.NginxHTTPSPort "443"}}:{{$.NginxHTTPSPort}}{{end}}{{else}}http://{{.Host}}{{if ne $.NginxHTTPPort "80"}}:{{$.NginxHTTPPort}}{{end}}{{end}}/"
        {{else -}}
        echo "Listen on: $${ORO_APP_PROTOCOL}://$${ORO_APP_DOMAIN}{{if and (ne .NginxHTTPPort "80") (ne .NginxHTTPPort "443")}}:{{.NginxHTTPPort}}{{end}}/"
        {{end -}}
        exec tail -f /dev/null
    volumes: *volumes-oro
    depends_on:
      "web":
        condition: service_started
      "consumer":
        condition: service_started
      "cron":
        condition: service_started

  web:
    <<: *oro-app
    environment:
      ORO_XDEBUG_ENABLED: "false"
      ORO_ENV: {{if eq .Type "demo"}}prod{{else}}${ORO_ENV:-dev}{{end}}
    command: nginx
    restart: unless-stopped
    healthcheck:
      test: "curl -If http://127.0.0.1:{{.NginxHTTPPort}}/"
      interval: 15s
      timeout: 30s
      start_period: 15s
    ports:
      - published: "{{.NginxHTTPPort}}"
        target: 80
      {{if .HasSsl -}}
      - published: "{{.NginxHTTPSPort}}"
        target: 443
      {{- end}}
    depends_on:
      "web-init":
        condition: service_completed_successfully
      "php-fpm-app":
        condition: service_healthy
    tmpfs:
      - /opt/oro-nginx
    volumes:
      {{if eq .Type "project" -}}
      - "{{.BundlePath}}:/var/www/oro"
      {{- else -}}
      - "oro_app:/var/www/oro"
      {{if eq .Type "bundle" -}}
      - "{{.BundlePath}}:/var/www/oro/src/{{.BundleNamespace}}"
      {{- end}}
      - "cache:/var/www/oro/var/cache:ro"
      - "public_storage:/var/www/oro/public/media:ro"
      - "private_storage:/var/www/oro/var/data:ro"
      {{- end}}
      - "./nginx.conf:/etc/nginx/http.d/default.conf:ro"
      - "./docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro"
      {{if .HasSsl -}}
      - "{{.CertsPath}}:/etc/nginx/certs:ro"
      {{- end}}

  volume-init:
    <<: *oro-app
    user: root
    command:
      - bash
      - -c
      - |
        echo "Initializing volumes and permissions for ${ORO_USER_RUNTIME:-www-data}..."
        mkdir -p bin config public src templates translations var assets var/cache var/logs var/data public/media
        chown -R ${ORO_USER_RUNTIME:-www-data} . bin config public src templates translations var assets var/cache var/logs var/data public/media 2>/dev/null || true
        chmod -R 777 var/cache var/logs var/data 2>/dev/null || true
        true
    environment:
      ORO_XDEBUG_ENABLED: "false"
    volumes: *volumes-oro

  web-init:
    <<: *oro-app
    command:
      - bash
      - -c
      - |
        echo "$$(jq '.properties.sites.propertyNames.pattern = ".*"' /opt/oro-nginx-tool/variables.schema.json 2>/dev/null || echo "{}")" > /opt/oro-nginx-tool/variables.schema.json 2>/dev/null || true
        /usr/local/bin/docker-entrypoint.sh nginx-init && sed -i '/gridfs/d; /mongo/d' /opt/oro-nginx/etc/sites-available/*.conf || true
    environment:
      ORO_XDEBUG_ENABLED: "false"
    depends_on:
      "php-fpm-app":
        condition: service_healthy
      "ws":
        condition: service_started
    tmpfs:
      - /opt/oro-nginx

  php-fpm-app:
    <<: *oro-app
    command: php-fpm
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    healthcheck:
      test: ["CMD", "php-fpm", "-t"]
      interval: 5s
      timeout: 30s
      start_period: 15s
    environment:
      ORO_ENV: {{if eq .Type "demo"}}prod{{else}}${ORO_ENV:-dev}{{end}}
      ORO_LOG_PATH: php://stderr
    depends_on:
      {{if .Postgres -}}
      "db":
        condition: service_healthy
      {{- end}}
      {{if .Mailpit -}}
      "mail":
        condition: service_started
      {{- end}}
      "volume-init":
        condition: service_completed_successfully
      {{if .Redis -}}
      "redis":
        condition: service_healthy
      {{- end}}
      {{if .RabbitMQ -}}
      "rabbitmq":
        condition: service_healthy
      {{- end}}
      {{if .Elasticsearch -}}
      "elasticsearch":
        condition: service_healthy
      {{- end}}
    volumes: *volumes-oro

  ws:
    <<: *oro-app
    command: websocket
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    init: true
    environment:
      ORO_ENV: {{if eq .Type "demo"}}prod{{else}}${ORO_ENV:-dev}{{end}}
      ORO_LOG_PATH: php://stderr
      ORO_XDEBUG_ENABLED: "false"
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes: *volumes-oro

  consumer:
    <<: *oro-app
    command: consumer
    restart: unless-stopped
    user: ${ORO_USER_RUNTIME:-www-data}
    init: true
    environment:
      ORO_ENV: {{if eq .Type "demo"}}prod{{else}}${ORO_ENV:-dev}{{end}}
      ORO_LOG_PATH: php://stderr
      ORO_XDEBUG_ENABLED: ${ORO_CONSUMER_XDEBUG_ENABLED:-false}
    depends_on:
      "php-fpm-app":
        condition: service_healthy
    volumes: *volumes-oro

  cron:
    <<: *oro-app
    user: ${ORO_USER_RUNTIME:-www-data}
    command: cron
    restart: unless-stopped
    ulimits:
      nofile:
        soft: 1024
        hard: 1048576
    environment:
      ORO_ENV: {{if eq .Type "demo"}}prod{{else}}${ORO_ENV:-dev}{{end}}
      ORO_LOG_PATH: php://stderr
      ORO_XDEBUG_ENABLED: ${ORO_CRON_XDEBUG_ENABLED:-false}
    volumes: *volumes-oro
    depends_on:
      "php-fpm-app":
        condition: service_healthy
      {{- if .Postgres}}
      "db":
        condition: service_healthy
      {{- end}}

  {{if .Postgres}}
  db:
    image: "postgres:{{.PostgresVersion}}"
    labels:
      com.symfony.server.service-prefix: ORO_DB
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${ORO_DB_NAME:-oro_db}
      POSTGRES_USER: ${ORO_DB_USER:-oro_db_user}
      POSTGRES_PASSWORD: ${ORO_DB_PASSWORD:-oro_db_pass}
      POSTGRES_ROOT_PASSWORD: ${ORO_DB_ROOT_PASSWORD:-oro_db_pass}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      start_period: 60s
    restart: unless-stopped
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      - pg_data:/var/lib/postgresql/data
  {{end}}
  {{if .Redis}}
  redis:
    image: "redis:{{.RedisVersion}}"
    hostname: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  {{end}}
  {{if and .RedisInsight (ne .Type "demo")}}
  redisinsight:
    image: redis/redisinsight:latest
    ports:
      - "8001:5540"
    restart: unless-stopped
    depends_on:
      - redis
  {{end}}
  {{if .Mailpit}}
  mail:
    image: axllent/mailpit
    hostname: mail
    ports:
      - "8025:8025"
      - "2025:1025"
    restart: unless-stopped
  {{end}}
  {{if .RabbitMQ}}
  rabbitmq:
    image: "rabbitmq:{{.RabbitMQVersion}}"
    hostname: rabbitmq
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      {{if ne .Type "demo" -}}
      - "15672:15672"
      {{- end}}
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: ${ORO_RABBITMQ_USER:-guest}
      RABBITMQ_DEFAULT_PASS: ${ORO_RABBITMQ_PASS:-guest}
  {{end}}
  {{if .Elasticsearch}}
  elasticsearch:
    image: "elasticsearch:{{.ElasticsearchVersion}}"
    hostname: elasticsearch
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200/_cluster/health?local=true || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - cluster.routing.allocation.disk.threshold_enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data
  {{end}}
  gotenberg:
    image: gotenberg/gotenberg:8.23.2
    ports:
      - "3000:3000"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://127.0.0.1:3000/health" ]
    restart: on-failure
  {{if and .Adminer (ne .Type "demo")}}
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    restart: unless-stopped
    depends_on:
      - db
  {{end}}
  {{if and .Kibana (ne .Type "demo")}}
  kibana:
    image: "kibana:{{.ElasticsearchVersion}}"
    ports:
      - "5601:5601"
    restart: unless-stopped
    depends_on:
      "elasticsearch":
        condition: service_healthy
    environment:
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
      XPACK_SECURITY_ENABLED: "false"
      XPACK_ENCRYPTED_SAVED_OBJECTS_ENCRYPTION_KEY: "a-32-character-minimum-encryption-key-for-kibana"
  {{end}}

volumes:
  oro_app:
  cache:
  public_storage:
  private_storage:
  pg_data:
  es_data:
